name: Build and Release Game - Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libasound2-dev \
            mesa-common-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            xorg-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libglfw3 \
            libglfw3-dev

      - name: Build game
        run: make

      - name: Export binary
        uses: actions/upload-artifact@v2
        with:
          name: game-binary
          path: game

      - name: Clean up
        run: make clean
